language: ruby
rvm: system
env:
- HOMEBREW_DEVELOPER=1
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode8.1
  - os: osx
    osx_image: xcode9.3beta
  exclude:
  - rvm: system
before_install:
- homebrew_repo="$(brew --repo)"
- sudo chown -R "$USER" "$homebrew_repo"
- git -C "$homebrew_repo" reset --hard origin/master
- brew update || brew update
- brew tap benesch/test-bot
- tapdir="$(brew --repo "$TRAVIS_REPO_SLUG")"
- mkdir -p "$tapdir"
- rm -rf "$tapdir"
- ln -s "$PWD" "$tapdir"
- ulimit -n 1024
- env | grep TRAVIS | tee /tmp/travis.env
install: true
script:
- brew test-bot
# This trickery prefers any just-built bottles so that we actually test
# this change. Otherwise, Homebrew just installs the bottles from the
# last known-good build. Setting HOMEBREW_BUILD_FROM_SOURCE=1 also works
# but is prohibitively slow.
- |
  for dep in $(brew deps -n os161-toolchain)
  do
    if [[ -f "$dep"*.bottle*.tar.gz ]]; then
      brew install "$dep"*.bottle*.tar.gz
    fi
  done
- travis_wait brew install os161-toolchain
- brew test os161-toolchain
addons:
  artifacts: true
notifications:
  webhooks: https://homebrew-os161.herokuapp.com
